alias zshconfig="vim ~/.zshrc"
alias zshrc="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias vimrc="vim ~/.vimrc"
alias alacrittyrc="vim ~/.config/alacritty/alacritty.yml"
alias i3conf="vim ~/.config/i3/config"
alias ls="ls --color --group-directories-first"
alias wallpapers="ranger ~/Pictures/Wallpapers"
alias Desk="cd ~/Desktop/"
alias Down="cd ~/Downloads/"
alias UK="cd ~/Desktop/MFF-Stuff/"
alias gitpage="chromium https://github.com/Marculonis21"
alias vims="vim -S"
alias pyserver="python3 -m https.server"
alias localhost="chromium http://localhost:8000"
alias cscompile="dotnet msbuild"
alias monogameCompile="dotnet publish -c Debug -r linux-x64 --self-contained"

mcscomplie () { mcs -recurse:'*.cs' -out:$1 ; } 
